config/routes.rb
Vanilla::Application.routes.draw do

  resource :user_session, :only => [ :new, :create, :destroy ]
  resource :password, :only => [ :new, :create, :edit, :update ]
  resource :registration, :only => [ :new, :create ]

  # API v1
  namespace :api, defaults: { format: :json } do
    resources :photos, only: [ :create, :show ]

    resource :profile, only: [ :update, :show ] do
      resources :notifications, only: [ :index, :destroy ]
      member do
        post :update_photo
      end
    end

    resources :users, :only => [ :show, :index ] do

      resources :posts, :only => [ :index, :create, :destroy ] do
        member do
          put 'recover'
        end
      end

      resources :friendships, :only => [ :create, :update, :destroy ]
    end

    resources :friendships, :only => [ :index ]

    #resource :search, only: [ :show ], :controller => 'search'

    resources :discussions, :only => [ :index, :new, :create ]
  end
  # end API v1

  # Static templates
  namespace :static, defaults: { format: :html } do
    match '*path' => 'templates#show'
  end

  # For logged in user
  constraints(LoggedInConstraint) do
    root :to => 'pages#home', :as => :authenticated_root
  end

  # Redirect to login form by default
  root :to => 'user_sessions#new'

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  remember_me_for 1.months
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_no_user, :only => [ :new, :create ]
  before_filter :require_user, :only => [ :destroy ]

  layout 'auth'

  # GET /user_session/new
  def new
    @user_session = UserSession.new
  end

  # POST /user_session
  def create
    @user_session = UserSession.new(params[:user_session])

    if @user_session.save
      redirect_to authenticated_root_url
    else
      render :new
    end
  end

  # DELETE /user_session
  def destroy
    current_user_session.destroy
    redirect_to root_url
  end

end

app/views/user_sessions/new.html.erb
<%= simple_form_for @user_session, :url => user_session_path, :html => { :class => 'form_vertical' } do |f| %>
  <%= f.input :email %>
  <%= f.input :password %>

  <%= f.input :remember_me, :as => :boolean %>

  <%= f.submit t('users.sign_in'), :class => 'button small' %>
  <%= link_to t('users.sign_up'), new_registration_path, :class => 'button small secondary' %>

  <ul class="side-nav">
    <li><%= link_to t('users.forgot_password'), new_password_path %></li>
  </ul>
<% end %>